### ISSUE TITLE
How to update coordinates in text box realtime while editing coordinate of bounding box?

### ISSUE THREAD

**Issue by Calm1100** [TaqBostan/react-image-label#10]
I have coordinate text box beside annotating image box.
While I'm editing points of bounding box, but it can update real time in text box
When I stop editing, it will be updated?
How I fix it?

**Comment by TaqBostan** [comment]
Hi,

I think we need to create an `onEdited` prop. So, each in every time a `shape` is edited, dragged, or rotated, the parent component can receive an up-to-date copy of it. We will implement it within a few days and keep you posted.

**Comment by Calm1100** [comment]
It's greate idea.
Please implement it soon.
Thank you so much.

**Comment by TaqBostan** [comment]
Please install version 1.4.0, and use `onEdited` prop as described in [README](https://github.com/TaqBostan/react-image-label#)

**Comment by Calm1100** [comment]
I updated you new feature.
Thank you so much.
