### ISSUE TITLE
is there a way to disable zooming when mouse wheel scrolling

### ISSUE THREAD

**Issue by begonia666** [TaqBostan/react-image-label#2]
Hi,

I just updated from version 0.2.8. I suddenly found that since v 1.0.0, the image component supports zoom in /out when mouse wheel scrolling, which is good but I am using Apple Magic mouse, it always trigger unexpected zooming action
😄

**Comment by TaqBostan** [comment]
Hi,

Sorry for the problem you mentioned. In the new version, users need to hold Ctrl/Command to zoom in/out. 
Please install version 1.1.3 and let me know if it solves the problem.

**Comment by begonia666** [comment]
Yes, 1.1.3 is working now, thank you for quick fixing
