### ISSUE TITLE
can i ask for source code of demo 1 and 2?

### ISSUE THREAD

**Issue by nattafahhm** [TaqBostan/react-image-label#3]
i didnt understand how to use this lib. could you provide code of your demo?

**Comment by TaqBostan** [comment]
Hi,

If you click the "Open Sandbox" button, you can access the source code:
https://codesandbox.io/s/f2gnwn
https://codesandbox.io/s/r9mw79

**Comment by nattafahhm** [comment]
Thanks! your tool has helped me a lot.

**Comment by TaqBostan** [comment]
Glad to hear that.
