### ISSUE TITLE
How can i change the color of polygon

### ISSUE THREAD

**Issue by nattafahhm** [TaqBostan/react-image-label#5]
I have many categories when I plot polygons or other types of labelling tools. I want to differentiate the colours and background label text for each category. Can you suggest a way to do that? For example, if a polygon represents blueberries, it should be blue with blue text, while a polygon representing strawberries should be red with red text. Thanks a lot.

**Comment by TaqBostan** [comment]
Hi

We have just released version 1.3.x. In this version, we are going to add some features for colorful annotations. First of all, you can draw/load/save colorful shapes in 1.3.0. Please take care of transparency yourself in 1.3.0 (I tried #27f17640, #276ef140, #efb9746b).

**Comment by knguyenrise8** [comment]
Is there a way to change the line color? was able to change the color with 1.3.x but need a way to change the line color

**Comment by nattafahhm** [comment]
Thanks a lot. I can fill colorful background annotations.  If we can change colors for strokes also, it would be nice:)

**Comment by TaqBostan** [comment]
Glad to hear that. I think we should use the background color and remove the transparency for strokes. Strokes have their own opacity (0.7).

**Comment by TaqBostan** [comment]
Please install version 1.3.4 for colored lines.
@nattafahhm 
@knguyenrise8
